name: CI/CD Docker

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: suryapermana92/heyva-outline

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.base
          tags: ${{ env.IMAGE_NAME }}:base
          push: true
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:base
          cache-to: type=inline

      - name: Build and push final image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          build-args: |
            BASE_IMAGE=${{ env.IMAGE_NAME }}:base
          tags: ${{ env.IMAGE_NAME }}:latest
          push: true
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
